import { createRouter, createWebHistory } from 'vue-router'

import Login from '../modulos/auth/Login.vue'
import Register from '../modulos/auth/Register.vue'
import Rol from '../modulos/roles/Roles.vue'
import Home from '../modulos/home/Home.vue'
import Usuarios from '../modulos/usuarios/Usuarios.vue'
import Menu from '../modulos/menu/Menu.vue'
import Sistemas from '../modulos/sistemas/Sistemas.vue'
import SistemaEditor from '../modulos/sistemas/SistemaEditor.vue'
import SistemaRuntime from '../modulos/sistemas/SistemaRuntime.vue'
import SistemaFrontendEmbed from '../modulos/sistemas/SistemaFrontendEmbed.vue'
import MainLayout from '../comun/layout/MainLayout.vue'
import AutoGeneratedView from '../modulos/menu/AutoGeneratedView.vue'

const routes = [
  { path: '/', redirect: '/login' },

  { path: '/login', component: Login },
  { path: '/register', component: Register },

  {
    path: '/',
    component: MainLayout,
    children: [
      {
        path: 'home',
        component: Home
      },
      {
        path: 'menu',
        component: Menu
      },
      {
        path: 'roles',
        component: Rol
      },
      {
        path: 'usuarios',
        component: Usuarios
      },
      {
        path: 'sistemas',
        component: Sistemas
      },
      {
        path: 'sistemas/:id',
        component: SistemaEditor,
        meta: { menuBase: '/sistemas' }
      },
      {
        path: 's/:slug',
        component: SistemaRuntime
      },
      {
        path: 's/:slug/:entity',
        component: SistemaRuntime
      },
      {
        path: 'frontend/:slug',
        component: SistemaFrontendEmbed
      },
      {
        path: ':autoPath(.*)*',
        component: AutoGeneratedView
      }
      // acá después van usuarios, roles, etc
    ]
  }
]

const router = createRouter({
  history: createWebHistory(),
  routes
})

router.beforeEach((to, from, next) => {
  const token = localStorage.getItem('token')
  const publicRoutes = ['/login', '/register']

  if (!token && !publicRoutes.includes(to.path)) {
    next('/login')
  } else {
    next()
  }
})

export default router
